# Donmoa 통합 계좌 설정 파일
# 계좌 정보: 계좌명, 종류, 매핑명

accounts:
  - name: "월급통장-기업"
    type: "은행"
    mapping_name: ["월급통장-기업"]

  - name: "생활비통장-국민"
    type: "은행"
    mapping_name: ["생활비통장-국민"]

  - name: "비상금통장-카카오"
    type: "은행"
    mapping_name: ["비상금통장-카카오"]

  - name: "주택청약-국민"
    type: "은행"
    mapping_name: ["주택청약-국민"]

  - name: "개인연금-미래"
    type: "증권"
    mapping_name: ["연금저축계좌(신)"]

  - name: "동적분배-삼성"
    type: "증권"
    mapping_name: ["종합매매"]

  - name: "국내배당-삼성"
    type: "증권"
    mapping_name: ["중개형ISA"]

  - name: "해외배당-키움"
    type: "증권"
    mapping_name: ["위탁종합"]

  - name: "개별주-토스"
    type: "증권"
    mapping_name: ["위탁"]

  - name: "퇴직연금-미래"
    type: "증권"
    mapping_name: ["미래에셋증권현금성자산", "개인형IRP"]

  - name: "퇴직연금-삼성"
    type: "증권"
    mapping_name: ["윤재영_IRP", "현금성자산(삼성증권)"]

  - name: "코인-업비트"
    type: "증권"
    mapping_name: ["업비트"]

  - name: "통합증권"
    type: "증권"
    mapping_name: ["증권"]

  - name: "네이버페이"
    type: "페이"
    mapping_name: ["네이버페이 머니"]

  - name: "카카오페이"
    type: "페이"
    mapping_name: ["카카오페이 머니 - 010*****446"]

  - name: "페이코"
    type: "페이"
    mapping_name: ["페이코포인트 - wh******@gmail.com"]
