# Donmoa 메인 설정 파일

# 통합 계좌 리스트 설정
unified_accounts:
  - "주거래계좌"
  - "주식투자계좌"
  - "펀드투자계좌"
  - "급여계좌"
  - "사업자계좌"
  - "해외투자계좌"

# Provider 설정 파일 경로
providers:
  domino: "config/providers/domino.yaml"
  banksalad: "config/providers/banksalad.yaml"

# 내보내기 설정
export:
  output_dir: "./data/export"
  file_format: "csv"
  encoding: "utf-8"

# 로깅 설정
logging:
  level: "INFO"
  file: "./data/logs/donmoa.log"
  console: true

# 전역 성능 설정
performance:
  default_retry_count: 3
  default_timeout: 30
  max_concurrent_providers: 5
