# Donmoa 설정 파일

# 스케줄 설정
schedule:
  enabled: true
  interval_hours: 24  # 24시간마다 실행
  start_time: "09:00"  # 매일 오전 9시에 실행

# 내보내기 설정
export:
  output_dir: "./export"  # CSV 파일 출력 디렉토리
  file_format: "csv"      # 출력 파일 형식
  encoding: "utf-8"       # 파일 인코딩

# Provider 설정
providers:
  securities:
    enabled: true
    retry_count: 3        # 재시도 횟수
    timeout: 30           # 타임아웃 (초)
  bank:
    enabled: true
    retry_count: 3
    timeout: 30
  exchange:
    enabled: true
    retry_count: 3
    timeout: 30

# 로깅 설정
logging:
  level: "INFO"           # 로그 레벨 (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  file: "./logs/donmoa.log"  # 로그 파일 경로
  console: true           # 콘솔 출력 여부
