# Donmoa 메인 설정 파일

# 통합 계좌 설정 파일 경로
accounts: "config/accounts.yaml"

# Provider 설정
providers:
  domino:
    input_dir: "./data/input"
    file_patterns: "*.mhtml"

  banksalad:
    input_dir: "./data/input"
    file_patterns: "*.xlsx"

# 내보내기 설정
export:
  output_dir: "./data/export"
  file_format: "csv"
  encoding: "utf-8"

# 로깅 설정
logging:
  level: "INFO"
  file: "./data/logs/donmoa.log"
  console: true

# 전역 성능 설정
performance:
  default_retry_count: 3
  default_timeout: 30
  max_concurrent_providers: 5
