# 뱅크샐러드 CSV Provider 설정
name: "banksalad_csv"
type: "bank"
enabled: true

# 계좌 매핑 설정
account_mapping:
  "주거래계좌": "신한은행 110-123-456789"
  "주식투자계좌": "국민은행 123-456-789012"
  "펀드투자계좌": "하나은행 123-456789-01234"
  "급여계좌": "우리은행 1002-123-456789"

# 수동 파일 설정
manual_files:
  enabled: true
  input_dir: "./data/input"
  file_patterns:
    balances: "*.xlsx"
    transactions: "*.xlsx"

# 파싱 설정
parsing:
  encoding: "utf-8"
  date_formats: ["%Y-%m-%d", "%Y/%m/%d", "%Y%m%d"]
  currency: "KRW"
  csv_delimiter: ","

# 성능 설정
performance:
  retry_count: 3
  timeout: 30
  max_file_size: "50MB"
