# 도미노 증권사 Provider 설정
name: "domino_securities"
type: "securities"
enabled: true

# 계좌 매핑 설정
account_mapping:
  "주거래계좌": "우리은행 123-456-7890"
  "주식투자계좌": "미래에셋증권 123456789"
  "펀드투자계좌": "KB증권 987654321"

# 수동 파일 설정
manual_files:
  enabled: true
  input_dir: "./data/input"
  file_patterns:
    balances: "*.mhtml"
    positions: "*.mhtml"
    transactions: "*.mhtml"

# 파싱 설정
parsing:
  encoding: "utf-8"
  date_formats: ["%Y-%m-%d", "%Y/%m/%d", "%Y.%m.%d"]
  currency: "KRW"

# 성능 설정
performance:
  retry_count: 3
  timeout: 30
  max_file_size: "10MB"
